### ISSUE TITLE
any good results?

### ISSUE THREAD

**Issue by hlsafin** [Bjacobwork/AnotherAgent57#1]
Quick question, Have you trained on Montezume's revenge and got decent results?

**Comment by Bjacobwork** [comment]
I got it to the first checkpoint, but I was training it on an old 1070, so I couldn't say why it took a while. There are better ways of building this though. If you are wondering if it works, yes, but I couldn't tell you the time requirements.

**Comment by Bjacobwork** [comment]
I would redesign the priority queue, model layout, weights server, then the training loop.
